# Generated by Django 6.0.3 on 2026-04-05 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100, verbose_name='Tên danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='TAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50, verbose_name='Tên thẻ')),
            ],
        ),
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=200, verbose_name='Tiêu đề bài viết')),
                ('CONTENT', models.TextField(verbose_name='Nội dung')),
                ('NGAYDANG', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('NGAYSUA', models.DateTimeField(auto_now=True, verbose_name='Ngày sỉnh sửa')),
                ('BAIVIET', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_app.category', verbose_name='Danh mục')),
                ('TACGIA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('THELOAI', models.ManyToManyField(blank=True, to='news_app.tag', verbose_name='Thẻ ')),
            ],
        ),
        migrations.CreateModel(
            name='COMMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOIDUNG', models.TextField(verbose_name='Nội dung bình luận')),
                ('NGAYBINHLUAN', models.DateTimeField(auto_now_add=True)),
                ('NGUOIBINHLUAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người bình luận')),
                ('THONGTIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news_app.post')),
            ],
        ),
    ]
