# Generated by Django 6.0.3 on 2026-04-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='HINHANH',
            field=models.ImageField(blank=True, null=True, upload_to='Image_file', verbose_name='Hình ảnh blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='THELOAI',
            field=models.ManyToManyField(blank=True, to='news_app.tag', verbose_name='Thẻ'),
        ),
    ]
