# Generated by Django 6.0.3 on 2026-04-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_post_hinhanh_alter_post_theloai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='HINHANH',
            field=models.ImageField(blank=True, null=True, upload_to='blog_photos', verbose_name='Hình ảnh blog'),
        ),
    ]
