# Generated by Django 6.0.3 on 2026-04-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_alter_post_hinhanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='HINHANH',
            field=models.ImageField(blank=True, null=True, upload_to='Image_file', verbose_name='Hình ảnh blog'),
        ),
    ]
